config/routes.rb
Webinst::Application.routes.draw do
  get "home/index"

  resources :arts
  
  match ':title/:id' => 'home#viewart', :as => :view_homeart

  resources :refs

  resources :autors

  resources :pics
  match 'pics/:id/view/:nombrefile' => 'pics#view', :as => :view_pic
  

   root :to => "home#index"

end

app/models/autor.rb
class Autor < ActiveRecord::Base
  belongs_to :pic
  has_and_belongs_to_many  :refs
  has_and_belongs_to_many  :arts
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  # GET /autors
  # GET /autors.xml
  def index
    @autors = Autor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @autors }
    end
  end

  # GET /autors/1
  # GET /autors/1.xml
  def show
    @autor = Autor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @autor }
    end
  end

  # GET /autors/new
  # GET /autors/new.xml
  def new
    @autor = Autor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @autor }
    end
  end

  # GET /autors/1/edit
  def edit
    @autor = Autor.find(params[:id])
  end

  # POST /autors
  # POST /autors.xml
  def create
    @autor = Autor.new(params[:autor])

    respond_to do |format|
      if @autor.save
        format.html { redirect_to(@autor, :notice => 'Autor was successfully created.') }
        format.xml  { render :xml => @autor, :status => :created, :location => @autor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @autor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /autors/1
  # PUT /autors/1.xml
  def update
    @autor = Autor.find(params[:id])

    respond_to do |format|
      if @autor.update_attributes(params[:autor])
        format.html { redirect_to(@autor, :notice => 'Autor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @autor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.xml
  def destroy
    @autor = Autor.find(params[:id])
    @autor.destroy

    respond_to do |format|
      format.html { redirect_to(autors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/views/autors/_form.html.erb
<%= form_for(@autor) do |f| %>
  <% if @autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
      <% @autor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :especialidad %><br />
    <%= f.text_field :especialidad %>
  </div>
  <div class="field">
      <%= f.label :pic_id %><br />
      <%= select("autor", "pic_id", Pic.find(:all, :order=>"titulo ASC").collect {|p| [ p.titulo + "(" + p.nombre + ")" , p.id ] }, {:include_blank => 'Seleccione una imagen'}) %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Editing autor</h1>

<%= render 'form' %>

<%= link_to 'Show', @autor %> |
<%= link_to 'Back', autors_path %>

app/views/autors/index.html.erb
<h1>Listing autors</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Especialidad</th>
    <th>Pic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @autors.each do |autor| %>
  <tr>
    <td><%= autor.nombre %></td>
    <td><%= autor.especialidad %></td>
    <td><%= autor.pic_id %></td>
    <td><%= link_to 'Show', autor %></td>
    <td><%= link_to 'Edit', edit_autor_path(autor) %></td>
    <td><%= link_to 'Destroy', autor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Autor', new_autor_path %>

app/views/autors/new.html.erb
<h1>New autor</h1>

<%= render 'form' %>

<%= link_to 'Back', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @autor.nombre %>
</p>

<p>
  <b>Especialidad:</b>
  <%= @autor.especialidad %>
</p>

<p>
  <b>Pic:</b>
  <%= image_tag url_img(@autor.pic.id,@autor.pic.nombre), :title => @autor.pic.titulo %>
</p>


<%= link_to 'Edit', edit_autor_path(@autor) %> |
<%= link_to 'Back', autors_path %>