config/routes.rb
Webinst::Application.routes.draw do
  get "home/index"

  resources :arts
  
  match ':title/:id' => 'home#viewart', :as => :view_homeart

  resources :refs

  resources :autors

  resources :pics
  match 'pics/:id/view/:nombrefile' => 'pics#view', :as => :view_pic
  

   root :to => "home#index"

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  has_many :autor
  has_many :ref
  has_and_belongs_to_many  :arts
  attr_reader :uploadfield
  validates :titulo, :tipo, :nombre ,:presence => {:message => "Debe ser completado"}
  validates_format_of :tipo, :with => /^image/, 
                            :message => "Solo pueden subirse imagenes"
  
  def uploadfield=(uploadfield)
    @uploadfield = uploadfield
    self.data = @uploadfield.read
    self.tipo = @uploadfield.content_type.chomp
    self.nombre = @uploadfield.original_filename
  end    
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  # GET /pics
  # GET /pics.xml
  def index
    @pics = Pic.all
    @titlePage ="Administracion de Imagenes"

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xml  { render :xml => @pics }
    end
  end

  

  # GET /pics/1
  # GET /pics/1.xml
  def show
    @pic = Pic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pic }
    end
  end

  # GET /pics/new
  # GET /pics/new.xml
  def new
    @pic = Pic.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pic }
    end
  end

  # GET /pics/1/edit
  def edit
    @pic = Pic.find(params[:id])
  end

  # POST /pics
  # POST /pics.xml
  def create
    @pic = Pic.new(params[:pic])    
    respond_to do |format|
      if @pic.save
        format.html { redirect_to(@pic, :notice => 'Se ha cargado la imagen correctamente.') }
        format.xml  { render :xml => @pic, :status => :created, :location => @pic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pics/1
  # PUT /pics/1.xml
  def update
    @pic = Pic.find(params[:id])

    respond_to do |format|
      if @pic.update_attributes(params[:pic])
        format.html { redirect_to(@pic, :notice => 'Se ha actualizado la imagen correctamente') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.xml
  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to(pics_url) }
      format.xml  { head :ok }
    end
  end
  
  # GET /pics/1/view/nombrefile
  def view
    @pic = Pic.find(params[:id])
    send_data(@pic.data, :filename => @pic.nombre, :type => @pic.tipo, :disposition => "inline")
  end
  
end

app/helpers/pics_helper.rb
module PicsHelper
  
end

app/views/pics/_form.html.erb
<%= form_for(@pic, :html=>{:multipart =>true}) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error se ha detectado", "errores se han detectado") %> :</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label "Imagen" %><br />
    <%= f.file_field "uploadfield" %>
  </div>
  <div class="actions">
    <%= f.submit 'Enviar'%>
  </div>
<% end %>

app/views/pics/_pic.html.erb
["<%= pic.nombre%>", "<%= url_img(pic.id,pic.nombre)%>"],

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<h1>Listado de Imagenes</h1>

<table>
  <tr> <th></th>
    <th>Titulo</th>
    <th>Nombre</th>
    <th>Tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pics.each do |pic| %>
  <tr>
  	<td align="center"><%= image_tag url_img(pic.id,pic.nombre), :title => pic.titulo ,:style=>"max-height:80px;max-width:80px;"%></td>
    <td><%= pic.titulo %></td>
    <td><%= pic.nombre %></td>
    <td><%= pic.tipo %></td>
    <td><%= link_to 'Show', pic %></td>
    <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
    <td><%= link_to 'Destroy', pic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Imagen', new_pic_path %>

app/views/pics/new.html.erb
<h1>Subir nueva imagen</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @pic.titulo %>
</p>

<p>
  <b>Nombre:</b>
  <%= @pic.nombre %>
</p>

<p>
  <b>Tipo:</b>
  <%= @pic.tipo %>
</p>

<p>
  <b>Data:</b><br/>
  <%= image_tag url_img(@pic.id,@pic.nombre)%><br/>
</p>


<%= link_to 'Editar', edit_pic_path(@pic) %> |
<%= link_to 'Volver', pics_path %>