config/routes.rb
Webinst::Application.routes.draw do
  get "home/index"

  resources :arts
  
  match ':title/:id' => 'home#viewart', :as => :view_homeart

  resources :refs

  resources :autors

  resources :pics
  match 'pics/:id/view/:nombrefile' => 'pics#view', :as => :view_pic
  

   root :to => "home#index"

end

app/models/art.rb
class Art < ActiveRecord::Base
  has_and_belongs_to_many  :refs
  has_and_belongs_to_many  :autors
  has_and_belongs_to_many  :pics
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  layout "backend"

  # GET /arts
  # GET /arts.xml
  def index
    @arts = Art.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @arts }
    end
  end

  # GET /arts/1
  # GET /arts/1.xml
  def show
    @art = Art.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @art }
    end
  end

  # GET /arts/new
  # GET /arts/new.xml
  def new
    @art = Art.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @art }
    end
  end

  # GET /arts/1/edit
  def edit
    @art = Art.find(params[:id])
  end

  # POST /arts
  # POST /arts.xml
  def create
    @art = Art.new(params[:art])

    respond_to do |format|
      if @art.save
        format.html { redirect_to(@art, :notice => 'Art was successfully created.') }
        format.xml  { render :xml => @art, :status => :created, :location => @art }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @art.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /arts/1
  # PUT /arts/1.xml
  def update
    @art = Art.find(params[:id])

    respond_to do |format|
      if @art.update_attributes(params[:art])
        format.html { redirect_to(@art, :notice => 'Art was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @art.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.xml
  def destroy
    @art = Art.find(params[:id])
    @art.destroy

    respond_to do |format|
      format.html { redirect_to(arts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo, :size=>131 %>
  </div>
  <div class="field">
    <%= f.label :resumen %><br />
    <%= f.text_area :resumen, :cols=>100, :rows=>5 %>
  </div>
  
  <div class="field"> 
		<p><label for="blog_content">Content</label><br/>
		<%= f.text_area :contenido, :cols => "100", :class=>"mceEditor"%></p>
  </div>
<div class="field">
    <%= f.label :autor%><br />
   <select id="autors" name="art[autor_ids][]" multiple="multiple" size="10" style="width: 250px;">
		<%= options_from_collection_for_select(Autor.find(:all), :id, :nombre, @art.autors.collect { |u| u.id}) %>
	</select>
	<br />                                    
  </div>
  
  <div class="field">
    <%= f.label :ref,"Referencias Bibliografias"%><br />
   <select id="refs" name="art[ref_ids][]" multiple="multiple" size="10" style="width: 250px;">
		<%= options_from_collection_for_select(Ref.find(:all), :id, :titulo, @art.refs.collect { |u| u.id}) %>
	</select>
	<br />                                    
  </div>
 
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<div id="beNuevo"><%= link_to 'Nuevo Articulo', new_art_path %></div>
<h1>Listado de Articulos</h1>

<br>
<% @arts.each do |art| %>
	<div>
		<div class="filaTitulo">			
			<div style="float: right;"><%= link_to 'Editar', edit_art_path(art) %>
				<%= link_to 'Borrar', art, :confirm => 'Estas seguro?', :method => :delete %>
			</div>
			<div><%= link_to art.titulo,art %></div>
		</div>
		<div>
			<%= art.resumen[0,250] %>
		</div>
	</div>
<% end %>
<br />

app/views/arts/new.html.erb
<h1>New art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo</b>
  <%= @art.titulo %>
</p>

<p>
  <b>Resumen</b>
  <%= @art.resumen %>
</p>

<p>
  <b>Contenido:</b>
  <%= @art.contenido %>
</p>


<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>