config/routes.rb
Webinst::Application.routes.draw do
  get "home/index"

  resources :arts
  
  match ':title/:id' => 'home#viewart', :as => :view_homeart

  resources :refs

  resources :autors

  resources :pics
  match 'pics/:id/view/:nombrefile' => 'pics#view', :as => :view_pic
  

   root :to => "home#index"

end

app/models/ref.rb
class Ref < ActiveRecord::Base
  belongs_to :pic
  has_and_belongs_to_many  :autors
  has_and_belongs_to_many  :arts
end

app/controllers/refs_controller.rb
class RefsController < ApplicationController
  # GET /refs
  # GET /refs.xml
  def index
    @refs = Ref.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @refs }
    end
  end

  # GET /refs/1
  # GET /refs/1.xml
  def show
    @ref = Ref.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ref }
    end
  end

  # GET /refs/new
  # GET /refs/new.xml
  def new
    @ref = Ref.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ref }
    end
  end

  # GET /refs/1/edit
  def edit
    @ref = Ref.find(params[:id])
  end

  # POST /refs
  # POST /refs.xml
  def create
    @ref = Ref.new(params[:ref])
    @ref.autors = params[:autors] ? Autor.find(params[:autors]) : []
  #video.categories = params[:categories] ? Category.find(params[:categories]) : []
    respond_to do |format|
      if @ref.save
        format.html { redirect_to(@ref, :notice => 'Ref was successfully created.') }
        format.xml  { render :xml => @ref, :status => :created, :location => @ref }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ref.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /refs/1
  # PUT /refs/1.xml
  def update
    @ref = Ref.find(params[:id])

    respond_to do |format|
      if @ref.update_attributes(params[:ref])
        format.html { redirect_to(@ref, :notice => 'Ref was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ref.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /refs/1
  # DELETE /refs/1.xml
  def destroy
    @ref = Ref.find(params[:id])
    @ref.destroy

    respond_to do |format|
      format.html { redirect_to(refs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/refs_helper.rb
module RefsHelper
end

app/views/refs/_form.html.erb
<%= form_for(@ref) do |f| %>
  <% if @ref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ref.errors.count, "error") %> prohibited this ref from being saved:</h2>

      <ul>
      <% @ref.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :detalle %><br />
    <%= f.text_field :detalle %>
  </div>
  <div class="field">
    <%= f.label :pic_id %><br />
    <%= select("ref", "pic_id", Pic.find(:all, :order=>"titulo ASC").collect {|p| [ p.titulo + "(" + p.nombre + ")" , p.id ] }, {:include_blank => 'Seleccione una imagen'}) %>
  </div>
  <div class="field">
    <%= f.label :autor%><br />
   <select id="autors" name="ref[autor_ids][]" multiple="multiple"
size="10" style="width: 250px;">
		<%= options_from_collection_for_select(Autor.find(:all), :id, :nombre, @ref.autors.collect { |u| u.id}) %>
	</select>                        <br />   
                                 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/refs/edit.html.erb
<h1>Editing ref</h1>

<%= render 'form' %>

<%= link_to 'Show', @ref %> |
<%= link_to 'Back', refs_path %>

app/views/refs/index.html.erb
<h1>Listing refs</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Detalle</th>
    <th>Pic</th>
    <th>Autor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @refs.each do |ref| %>
  <tr>
    <td><%= ref.titulo %></td>
    <td><%= ref.detalle %></td>
    <td><%= ref.pic_id %></td>
    <td><%= ref.autors.collect { |u| u.nombre + " "} %></td>
    <td><%= link_to 'Show', ref %></td>
    <td><%= link_to 'Edit', edit_ref_path(ref) %></td>
    <td><%= link_to 'Destroy', ref, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ref', new_ref_path %>

app/views/refs/new.html.erb
<h1>New ref</h1>

<%= render 'form' %>

<%= link_to 'Back', refs_path %>

app/views/refs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @ref.titulo %>
</p>

<p>
  <b>Detalle:</b>
  <%= @ref.detalle %>
</p>

<p>
  <b>Pic:</b>
  <%= @ref.pic_id %>
</p>

<p>
  <b>Autor:</b>
  
</p>


<%= link_to 'Edit', edit_ref_path(@ref) %> |
<%= link_to 'Back', refs_path %>